// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
const sounds = {
    step2: require("./audio/step-2.flac"),
  step1: require("./audio/step-1.flac"),
  fleshHit4: require("./audio/flesh-hit-4.flac"),
  fleshHit3: require("./audio/flesh-hit-3.flac"),
  fleshHit2: require("./audio/flesh-hit-2.flac"),
  fleshHit1: require("./audio/flesh-hit-1.flac")
};
export type SoundName = keyof typeof sounds;

const images = {
    player: require("./images/player.png"),
  hallwayFloor: require("./images/hallway-floor.png"),
  favicon: require("./images/favicon.png"),
  enemy: require("./images/enemy.png"),
  player8: require("./images/player/player8.png"),
  player7: require("./images/player/player7.png"),
  player6: require("./images/player/player6.png"),
  player5: require("./images/player/player5.png"),
  player4: require("./images/player/player4.png"),
  player3: require("./images/player/player3.png"),
  player2: require("./images/player/player2.png"),
  player1: require("./images/player/player1.png"),
  teacherGym8: require("./images/enemies/teacher-gym8.png"),
  teacherGym7: require("./images/enemies/teacher-gym7.png"),
  teacherGym6: require("./images/enemies/teacher-gym6.png"),
  teacherGym5: require("./images/enemies/teacher-gym5.png"),
  teacherGym4: require("./images/enemies/teacher-gym4.png"),
  teacherGym3: require("./images/enemies/teacher-gym3.png"),
  teacherGym2: require("./images/enemies/teacher-gym2.png"),
  teacherGym1: require("./images/enemies/teacher-gym1.png")
};
export type ImageName = keyof typeof images;

const fonts = {
    rubikIsoRegular: require("./fonts/RubikIso-Regular.ttf")
};
export type FontName = keyof typeof fonts;

const levels = {
    hallway: require("./levels/hallway.json")
};
export type LevelName = keyof typeof levels;

export const RESOURCES = { sounds, images, fonts };
