// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
const sounds = {
    fleshHit4: require("./audio/flesh-hit-4.flac"),
  fleshHit3: require("./audio/flesh-hit-3.flac"),
  fleshHit2: require("./audio/flesh-hit-2.flac"),
  fleshHit1: require("./audio/flesh-hit-1.flac")
};
export type SoundName = keyof typeof sounds;

const images = {
    player: require("./images/player.png"),
  hallwayFloor: require("./images/hallway-floor.png"),
  favicon: require("./images/favicon.png"),
  enemy: require("./images/enemy.png")
};
export type ImageName = keyof typeof images;

const fonts = {
    rubikIsoRegular: require("./fonts/RubikIso-Regular.ttf")
};
export type FontName = keyof typeof fonts;

const levels = {
    hallway: require("./levels/hallway.json")
};
export type LevelName = keyof typeof levels;

export const RESOURCES = { sounds, images, fonts };
