// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
declare const fnt_kgBrokenVesselsSketch: string;
export default fnt_kgBrokenVesselsSketch;
