// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
declare const img_classroomFloorHerringbone: string;
export default img_classroomFloorHerringbone;
