// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
declare const snd_rawFootstepsToeHeel: string;
export default snd_rawFootstepsToeHeel;
